title: A blog on science
author: Stathis Kamperis
email: ekamperi@gmail.com
description: >
  A blog on things I’m interested in such as mathematics, physics, programming,
  machine learning, data science, and radiation oncology.

show_excerpts: false
show_drafts: true

makdown: kramdown
kramdown:
  math_engine: mathjax
  math_enging_opts:
    preview: true
    
url: "https://ekamperi.github.io"

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: stathisktw
    github: ekamperi

remote_theme: jekyll/minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
paginate_path: posts/page:num/

header_pages:
  - about.md
  - archive.md
  - tags.md

google_analytics: UA-145393080-1

#disqus:
#    shortname: https-ekamperi-github-io


algolia:
   application_id: HS5PEB5VJV
   index_name: ekamperi_github_io
   search_only_api_key: a4849f630ca2026df0cd91d0814d0db7
 
   