theme: minima
makdown: kramdown
kramdown:
  math_engine: mathjax
  math_enging_opts:
    preview: true

header_pages:
  - about.md
  - portfolio.md

minima:
  social_links:
    twitter: stathisktw
    github: ekamperi
    facebook: Stathis Kamperis
 