title: A blog on science
author: Stathis Kamperis
email: ekamperi@gmail.com
description: >
  A blog on things I’m interested in such as mathematics, physics, programming,
  machine learning and radiotherapy.

show_excerpts: true
show_drafts: true

makdown: kramdown
kramdown:
  math_engine: mathjax
  math_enging_opts:
    preview: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: stathisktw
    github: ekamperi

remote_theme: jekyll/minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

gems:
  - jekyll-paginate

paginate: 2
paginate_path: posts/page:num/

header_pages:
  - about.md
  - archive.md

google_analytics: UA-145393080-1

disqus:
    shortname: https-ekamperi-github-io

