title: A blog on science
author: Stathis Kamperis
email: ekamperi@gmail.com
description: >
  A blog on things I’m interested in such as mathematics, physics, programming,
  machine learning and radiotherapy.

show_excerpts: true
show_drafts: true

makdown: kramdown
kramdown:
  math_engine: mathjax
  math_enging_opts:
    preview: true

header_pages:
  - about.md

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: stathisktw
    github: ekamperi

header_pages:
  about.html
  archive.html

remote_theme: jekyll/minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-145393080-1

